before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq nodejs
  - sudo apt-get install -qq npm
  - sudo ln -s /usr/bin/node /usr/bin/nodejs
  - sudo apt-get install -qq openjdk-6-jre
  - "PACKAGE=rhino1_7R4; curl -L -O https://github.com/downloads/mozilla/rhino/$PACKAGE.zip && sudo unzip $PACKAGE -d /opt/ && rm $PACKAGE.zip"
  - "PACKAGE=rhino1_7R4; echo -e '#!/bin/sh\\njava -jar /opt/rhino1_7R4/js.jar $@' | sudo tee /usr/local/bin/rhino && sudo chmod +x /usr/local/bin/rhino"
install:
  - git clone https://github.com/sstephenson/bats.git
script: bats/bin/bats --tap test/js.bats
language: c
notifications:
  email:
    on_success: never
