before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y node rhino
install:
  - git clone https://github.com/sstephenson/bats.git
script: bats/bin/bats --tap test
# skips unnecessary Ruby-specific setup
language: c
notifications:
  email:
    on_success: never
