install:
  - git clone https://github.com/sstephenson/bats.git
  - apt-get install node
  - apt-get install rhino
script: bats/bin/bats --tap test
# skips unnecessary Ruby-specific setup
language: c
notifications:
  email:
    on_success: never
